services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: 'fireart'
    ports:
      - 5432:5432
    volumes:
      - database_data:/vat/lib/postgresql/data
  smtp:
    image: rnwood/smtp4dev
    ports:
      - 15080:80
      - 2525:25
volumes:
  database_data:
