apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fireart

resources:
  - './db.yaml'
  - './ingress.yaml'
  - './api.yaml'

configMapGenerator:
  - envs:
      - .env.api
    name: api-config