apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-7a6a29c5-1747881953 # {"$imagepolicy": "flux-system:fireart:tag"}
