apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-d8fea1f0-1747878518 # {"$imagepolicy": "flux-system:fireart:tag"}
