apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-25f6c31e-1747875037 # {"$imagepolicy": "flux-system:fireart:tag"}
