apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-c6f44211-1747877661 # {"$imagepolicy": "flux-system:fireart:tag"}
