apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-f1b7c34c-1747892144 # {"$imagepolicy": "flux-system:fireart:tag"}
