apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-4f3c7339-1747895604 # {"$imagepolicy": "flux-system:fireart:tag"}
