apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-ed8e8c91-1747892976 # {"$imagepolicy": "flux-system:fireart:tag"}
