apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-1f625a5d-1747892568 # {"$imagepolicy": "flux-system:fireart:tag"}
