apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-b2e7d793-1747869275 # {"$imagepolicy": "flux-system:fireart:tag"}
