apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-38d64e1b-1748448872 # {"$imagepolicy": "flux-system:fireart:tag"}
