apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-d5e76a36-1747873704 # {"$imagepolicy": "flux-system:fireart:tag"}
