apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secrets.yaml
images:
  - name: docker.longu.dev/fireart/api
    newTag: develop-b702e9a1-1747880239 # {"$imagepolicy": "flux-system:fireart:tag"}
