apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: api
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: vault-universal-auth
        secretNamespace: vault
      secretsScope:
        envSlug: dev
        projectSlug: fireart-xa-kt
        secretsPath: /api
  managedSecretReference:
    secretName: api-secrets
    secretNamespace: fireart
    creationPolicy: Owner
    template:
      includeAllSecrets: true